# Namespace Definition
apiVersion: v1
kind: Namespace
metadata:
  name: jhub
---
# Persistent Volume Claim (PVC) for JupyterHub using CephFS
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
  namespace: jhub
spec:
  storageClassName: rook-cephfs  # Ensure this matches your CephFS storage class
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
# ConfigMap for JupyterHub Configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: jupyterhub-config
  namespace: jhub
data:
  jupyterhub_config.py: |
    c.JupyterHub.authenticator_class = 'jupyterhub.auth.DummyAuthenticator'
    c.DummyAuthenticator.allowed_users = {'test'}
    c.DummyAuthenticator.password = 'test'
    c.ConfigurableHTTPProxy.api_port = 8001
    c.ConfigurableHTTPProxy.internal_port = 8002
    c.JupyterHub.ip = '0.0.0.0'
    c.JupyterHub.port = 8000
    c.Spawner.http_timeout = 120
---
# JupyterHub Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyterhub
  namespace: jhub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyterhub
  template:
    metadata:
      labels:
        app: jupyterhub
    spec:
      containers:
      - name: jupyterhub
        image: jupyterhub/jupyterhub:latest
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: jupyterhub-config-volume
          mountPath: /srv/jupyterhub/jupyterhub_config.py  # Full file path
          subPath: jupyterhub_config.py
        - name: jupyterhub-pvc
          mountPath: /home/jupyter  # This ensures persistent storage for user data
        lifecycle:
          postStart:
            exec:
              command:
                - /bin/sh
                - -c
                - |
                  echo "Installing required Python packages..."
                  pip install --no-cache-dir jupyter_server jupyterlab &&
                  echo "Starting JupyterHub..." &&
                  useradd -m test
        command:
        - sh
        - -c
        - |
          echo "Launching JupyterHub..."
          jupyterhub -f /srv/jupyterhub/jupyterhub_config.py
      volumes:
      - name: jupyterhub-config-volume
        configMap:
          name: jupyterhub-config
      - name: jupyterhub-pvc
        persistentVolumeClaim:
          claimName: my-pvc  # Uses the CephFS PVC for storage
---
# JupyterHub Service (NodePort for External Access)
apiVersion: v1
kind: Service
metadata:
  name: jupyterhub-service
  namespace: jhub
spec:
  selector:
    app: jupyterhub
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30008  # Ensure this port is open in your firewall
  type: NodePort
